//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkUserSurvey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet checkUserSurvey(int idsurveyquestion, int idriparazione, int iduser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllFornitori", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAllFornitori();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFornitori", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getFornitori(int FornitoriId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContratto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetContratto(string targa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRicambi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRicambi(int idriparazione);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFornitorisByFilter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getFornitorisByFilter(double lat, double lng, int distance, string filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFornitorisByDistance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getFornitorisByDistance(double lat, double lng, int distance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getRiparazione", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getRiparazione(string targa, int iduser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSurveyQuestion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getSurveyQuestion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserSurvey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getUserSurvey(int riparazioneID, int iduser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertUserSurvey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool insertUserSurvey(int riparazioneID, int iduser, string questionID, string answer, string memo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateDeviceToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool updateDeviceToken(string deviceToken, int idUser, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/varifyUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet varifyUser(string TARGA, string DOSSIER);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPushMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPushMessage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePushMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeletePushMessage(int idpushMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIdUserToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetIdUserToken(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPushMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertPushMessage(int idusertoken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllAppointments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAllAppointments(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAppointmentByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAppointmentByID(int idAppointment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRiparazione", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateRiparazione(int idriparazione, string dtConsegnaRAC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAppointment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool InsertAppointment(string Name, string ContactNo, System.DateTime ProposedDate1, string ProposedDate2, string ProposedDate3, int idUser, string fornitori, string indrizzio, bool tagliando, bool revisione, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCambioGommaByCodiceContratto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getCambioGommaByCodiceContratto(string CodiceContratto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultaByCodiceContratto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMultaByCodiceContratto(string codiceContratto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrdine(string codiceContratto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDocumentazione", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDocumentazione();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSinistriById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSinistriById(int idSinistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSinistriByCodiceContratto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSinistriByCodiceContratto(string codiceContratto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllegatoSinistroBySinistroId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllegatoSinistroBySinistroId(int idSinistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetScadenziariByCodiceContratto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetScadenziariByCodiceContratto(string codiceContratto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCarburanteByTarga", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCarburanteByTarga(string targa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCartaCarburanteDettaglioByTarga", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCartaCarburanteDettaglioByTarga(string targa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTerminationByCodiceContratto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTerminationByCodiceContratto(string codiceContratto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeliveryByCodiceContratto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDeliveryByCodiceContratto(string codiceContratto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : demo.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<demo.ServiceReference1.Service1Soap>, demo.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet checkUserSurvey(int idsurveyquestion, int idriparazione, int iduser) {
            return base.Channel.checkUserSurvey(idsurveyquestion, idriparazione, iduser);
        }
        
        public System.Data.DataSet getAllFornitori() {
            return base.Channel.getAllFornitori();
        }
        
        public System.Data.DataSet getFornitori(int FornitoriId) {
            return base.Channel.getFornitori(FornitoriId);
        }
        
        public System.Data.DataSet GetContratto(string targa) {
            return base.Channel.GetContratto(targa);
        }
        
        public System.Data.DataSet GetRicambi(int idriparazione) {
            return base.Channel.GetRicambi(idriparazione);
        }
        
        public System.Data.DataSet getFornitorisByFilter(double lat, double lng, int distance, string filter) {
            return base.Channel.getFornitorisByFilter(lat, lng, distance, filter);
        }
        
        public System.Data.DataSet getFornitorisByDistance(double lat, double lng, int distance) {
            return base.Channel.getFornitorisByDistance(lat, lng, distance);
        }
        
        public System.Data.DataSet getRiparazione(string targa, int iduser) {
            return base.Channel.getRiparazione(targa, iduser);
        }
        
        public System.Data.DataSet getSurveyQuestion() {
            return base.Channel.getSurveyQuestion();
        }
        
        public System.Data.DataSet getUserSurvey(int riparazioneID, int iduser) {
            return base.Channel.getUserSurvey(riparazioneID, iduser);
        }
        
        public bool insertUserSurvey(int riparazioneID, int iduser, string questionID, string answer, string memo) {
            return base.Channel.insertUserSurvey(riparazioneID, iduser, questionID, answer, memo);
        }
        
        public bool updateDeviceToken(string deviceToken, int idUser, string tableName) {
            return base.Channel.updateDeviceToken(deviceToken, idUser, tableName);
        }
        
        public System.Data.DataSet varifyUser(string TARGA, string DOSSIER) {
            return base.Channel.varifyUser(TARGA, DOSSIER);
        }
        
        public System.Data.DataSet GetPushMessage() {
            return base.Channel.GetPushMessage();
        }
        
        public bool DeletePushMessage(int idpushMessage) {
            return base.Channel.DeletePushMessage(idpushMessage);
        }
        
        public System.Data.DataSet GetIdUserToken(int idUser) {
            return base.Channel.GetIdUserToken(idUser);
        }
        
        public bool InsertPushMessage(int idusertoken) {
            return base.Channel.InsertPushMessage(idusertoken);
        }
        
        public System.Data.DataSet getAllAppointments(int idUser) {
            return base.Channel.getAllAppointments(idUser);
        }
        
        public System.Data.DataSet getAppointmentByID(int idAppointment) {
            return base.Channel.getAppointmentByID(idAppointment);
        }
        
        public bool UpdateRiparazione(int idriparazione, string dtConsegnaRAC) {
            return base.Channel.UpdateRiparazione(idriparazione, dtConsegnaRAC);
        }
        
        public bool InsertAppointment(string Name, string ContactNo, System.DateTime ProposedDate1, string ProposedDate2, string ProposedDate3, int idUser, string fornitori, string indrizzio, bool tagliando, bool revisione, string reason) {
            return base.Channel.InsertAppointment(Name, ContactNo, ProposedDate1, ProposedDate2, ProposedDate3, idUser, fornitori, indrizzio, tagliando, revisione, reason);
        }
        
        public System.Data.DataSet getCambioGommaByCodiceContratto(string CodiceContratto) {
            return base.Channel.getCambioGommaByCodiceContratto(CodiceContratto);
        }
        
        public System.Data.DataSet GetMultaByCodiceContratto(string codiceContratto) {
            return base.Channel.GetMultaByCodiceContratto(codiceContratto);
        }
        
        public System.Data.DataSet GetOrdine(string codiceContratto) {
            return base.Channel.GetOrdine(codiceContratto);
        }
        
        public System.Data.DataSet GetDocumentazione() {
            return base.Channel.GetDocumentazione();
        }
        
        public System.Data.DataSet GetSinistriById(int idSinistro) {
            return base.Channel.GetSinistriById(idSinistro);
        }
        
        public System.Data.DataSet GetSinistriByCodiceContratto(string codiceContratto) {
            return base.Channel.GetSinistriByCodiceContratto(codiceContratto);
        }
        
        public System.Data.DataSet GetAllegatoSinistroBySinistroId(int idSinistro) {
            return base.Channel.GetAllegatoSinistroBySinistroId(idSinistro);
        }
        
        public System.Data.DataSet GetScadenziariByCodiceContratto(string codiceContratto) {
            return base.Channel.GetScadenziariByCodiceContratto(codiceContratto);
        }
        
        public System.Data.DataSet GetCarburanteByTarga(string targa) {
            return base.Channel.GetCarburanteByTarga(targa);
        }
        
        public System.Data.DataSet GetCartaCarburanteDettaglioByTarga(string targa) {
            return base.Channel.GetCartaCarburanteDettaglioByTarga(targa);
        }
        
        public System.Data.DataSet GetTerminationByCodiceContratto(string codiceContratto) {
            return base.Channel.GetTerminationByCodiceContratto(codiceContratto);
        }
        
        public System.Data.DataSet GetDeliveryByCodiceContratto(string codiceContratto) {
            return base.Channel.GetDeliveryByCodiceContratto(codiceContratto);
        }
    }
}
